const GET_MOVIES= 'GET_MOVIES';
const GET_GENRES = 'GET_GENRES';
const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
const GET_GENRE_DETAILS = 'GET_GENRE_DETAILS'

export {GET_GENRES, GET_MOVIES, GET_GENRE_DETAILS, GET_MOVIE_DETAILS}